const FOODS_API = '/api/foods';
const USERS_API = '/api/users';

const SIGN_UP_ENDPOINT = '/signup';
const LOGIN_ENDPOINT = '/login';
const UPDATE_DAILY_THRESHOLD_ENDPOINT = '/updateDailyThresHold';
const GET_USERS_LIST_ENDPOINT = '/';
const GET_USER_DETAILS = '/getUserDetails';

const CREATE_FOOD = '/';
const GET_FOODS_LIST_BY_USER_ID = '/user/:uid';
const UPDATE_FOOD = '/:fid';
const DELETE_FOOD = '/';
const GET_FOOD_DETAILS = '/:fid';
const GET_ALL_FOODS_LIST = '/all';

exports.FOODS_API = FOODS_API;
exports.USERS_API = USERS_API;
exports.SIGN_UP_ENDPOINT = SIGN_UP_ENDPOINT;
exports.LOGIN_ENDPOINT = LOGIN_ENDPOINT;
exports.UPDATE_DAILY_THRESHOLD_ENDPOINT = UPDATE_DAILY_THRESHOLD_ENDPOINT;
exports.GET_USERS_LIST_ENDPOINT = GET_USERS_LIST_ENDPOINT;
exports.CREATE_FOOD = CREATE_FOOD;
exports.GET_FOODS_LIST_BY_USER_ID = GET_FOODS_LIST_BY_USER_ID;
exports.DELETE_FOOD = DELETE_FOOD;
exports.UPDATE_FOOD = UPDATE_FOOD;
exports.GET_FOOD_DETAILS = GET_FOOD_DETAILS;
exports.GET_USER_DETAILS = GET_USER_DETAILS;
exports.GET_ALL_FOODS_LIST = GET_ALL_FOODS_LIST;
